name: CI
on:
  push:
    branches:
      - "**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
